version: '3'

# Airflow 공통 설정 (services 밖에 위치)
x-airflow-common: &airflow-common
  build: 
    context: ./
    dockerfile: ./services/airflow/Dockerfile
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    JAVA_HOME: /usr/lib/jvm/default-java
    ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  volumes:
    - ./src/batch/dags:/opt/airflow/dags
    - ./src/batch/logs:/opt/airflow/logs
    - ./src/batch/config:/opt/airflow/config
    - ./src/batch/plugins:/opt/airflow/plugins
    - ./src/batch/dags/scripts:/opt/airflow/dags/scripts
    - ./src/batch/data:/opt/airflow/data
    - ./src/batch/output:/opt/airflow/output
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres-airflow:
      condition: service_healthy
  networks:
    - airflow

services:
  # ubuntu-python:
  #   build: 
  #     context: ./
  #     dockerfile: ./services/ubuntu-python/Dockerfile
  #   container_name: ubuntu_python
  #   working_dir: /opt/workspace
  #   volumes:
  #     - ubuntu_workspace:/opt/workspace
  #     - type: bind
  #       source: ./src/up_test_codes
  #       target: /opt/workspace/up_test_codes
  #     - type: bind
  #       source: ./src/up_ingest_codes
  #       target: /opt/workspace/up_ingest_codes
  #   depends_on:
  #     - postgres
  #   tty: true

  postgres:
    build: ./services/postgres
    container_name: postgres
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - airflow

  kafka:
    build: 
      context: ./
      dockerfile: ./services/kafka/Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    working_dir: /opt/workspace
    volumes:
      - type: bind
        source: ./src/kafka_producer
        target: /opt/workspace/kafka_producer
      - type: bind
        source: ./src/kafka_test_codes
        target: /opt/workspace/kafka_test_codes
      - type: bind
        source: ./src/up_ingest_codes/article_extractors.py
        target: /opt/workspace/article_extractors.py
      - type: bind
        source: ./.env
        target: /opt/workspace/.env
    depends_on:
      - zookeeper
    networks:
      - airflow

  flink:
    build: 
      context: ./
      dockerfile: ./services/flink/Dockerfile
    container_name: flink
    ports:
      - "8081:8081"
    working_dir: /opt/workspace
    volumes:
      - type: bind
        source: ./src/flink_test_codes
        target: /opt/workspace/flink_test_codes
      - type: bind
        source: ./src/flink_consumer
        target: /opt/workspace/flink_consumer
      - type: bind
        source: ./services/flink/config
        target: /opt/flink/lib
      - type: bind
        source: ./.env
        target: /opt/workspace/.env
      - type: bind
        source: ./src/batch/data/realtime
        target: /opt/batch/data/realtime
    environment:
      - KAFKA_CONNECTOR_PATH=/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar
    depends_on:
      - kafka
      - postgres
    tty: true
    networks:
      - airflow
  
  # spark:
  #   build:
  #     context: ./
  #     dockerfile: ./services/spark/Dockerfile
  #   container_name: spark
  #   ports:
  #     - "8082:8082"  # Spark Master Web UI
  #     - "4040:4040"  # Spark Application Web UI
  #   working_dir: /opt/workspace
  #   volumes:
  #     - type: bind
  #       source: ./src/spark_test_codes
  #       target: /opt/workspace/spark_test_codes
  #   environment:
  #     - SPARK_MASTER_HOST=spark
  #   tty: true
  #   networks:
  #     - airflow

  django:
    build:
      context: ./
      dockerfile: ./services/django/Dockerfile
    container_name: django
    ports:
      - "8000:8000"  # Django 백엔드 포트
    volumes:
      - type: bind
        source: ./src/vue_django_codes/news_backend
        target: /app
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./services/django/local_settings.py
        target: /app/news_backend/local_settings.py
      - type: bind
        source: ./services/django/setup.sh
        target: /app/setup.sh
    environment:
      - DB_HOST=postgres
      - DB_NAME=news
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: always
    networks:
      - airflow
  
  vue:
    build:
      context: ./
      dockerfile: ./services/vue/Dockerfile
    container_name: vue
    ports:
      - "3000:3000"  # Vite 개발 서버 포트
    volumes:
      - type: bind
        source: ./src/vue_django_codes/news_front
        target: /app
      - vue_node_modules:/app/node_modules
    environment:
      - VITE_BASE_URL=http://localhost:8000
    depends_on:
      django:
        condition: service_healthy
    networks:
      - airflow

  # Airflow 관련 서비스 추가
  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow

  redis:
    image: redis:7.2-bookworm
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - airflow

  # Spark Master-Worker 아키텍처로 변경
  spark-master:
    build:
      context: ./
      dockerfile: ./services/spark_cluster/Dockerfile
    container_name: spark-master
    ports:
      - "8083:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master 통신 포트
    environment:
      - SPARK_MODE=master
    volumes:
      - ./src/batch/dags/scripts:/opt/bitnami/spark/scripts
      - ./src/batch/data:/opt/bitnami/spark/data
      - ./src/batch/output:/opt/bitnami/spark/output
    networks:
      - airflow

  spark-worker:
    build:
      context: ./
      dockerfile: ./services/spark_cluster/Dockerfile
    container_name: spark-worker
    ports:
      - "8084:8081"  # Spark Worker Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./src/batch/dags/scripts:/opt/bitnami/spark/scripts
      - ./src/batch/data:/opt/bitnami/spark/data
      - ./src/batch/output:/opt/bitnami/spark/output
    depends_on:
      - spark-master
    networks:
      - airflow

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    environment:
      <<: *airflow-common-env
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      spark-master:
        condition: service_started

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID:-50000}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ./src/batch:/sources

  flower:
    <<: *airflow-common
    container_name: flower
    command: celery flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

volumes:
  pgdata:
  postgres-db-volume:
  ubuntu_workspace:
  vue_node_modules:

networks:
  airflow:
    driver: bridge